### ISSUE TITLE
How is the dataset divided?

### ISSUE THREAD

**Issue by yuwenyouhaoran** [XuShenLZ/ParkSim#1]
I'm sorry that the previous description was not clear.

I just cloned the code and used the default parameters and DJI_0007~DJI_0014 in the code for training, but the results obtained are different from those in the paper. May I ask which part of the data was used for training to get the results in the paper?

The dataset was applied by my classmates in the same lab, and I'm doing similar research with him, therefore using the same dataset.

**Comment by XuShenLZ** [comment]
Thanks for your interest! I don't think we have received the dataset requests from you. May I know which data files did you use?

**Comment by yuwenyouhaoran** [comment]
30 scenes in DLP dataset

**Comment by yuwenyouhaoran** [comment]
> Thanks for your interest! I don't think we have received the dataset requests from you. May I know which data files did you use? Also, could you please describe your experiment steps clearly?

I'm sorry that the previous description was not clear.

I just cloned the code and used the default parameters and DJI_0007~DJI_0014 in the code for training, but the results obtained are different from those in the paper. May I ask which part of the data was used for training to get the results in the paper?

The dataset was applied by my classmates in the same lab, and I'm doing similar research with him, therefore using the same dataset.

**Comment by XuShenLZ** [comment]
The [default code](https://github.com/XuShenLZ/ParkSim/blob/a043581b9f2ecaec579d308c51f43ab3e0675b6e/python/parksim/trajectory_predict/data_processing/create_dataset.py#L138) is only using DJI_0006 for fast execution. In the paper, we are using DJI_0007~0022 which results in 57500 total data points. Of those, about 51750 were used for training, and the rest for validation.

So you might want to change the code to be `names = ["DJI_" + str(i).zfill(4) for i in range(7, 23)]`

In terms of the dataset, please limit the circulation inside your lab. Please let others submit another request if they are interested. Thanks!

**Comment by yuwenyouhaoran** [comment]
Thank you very much for your help in your busy schedule! I have fully understood the process of your experiment through your detailed explanation.
