### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by HyzenthlayER** [XuShenLZ/ParkSim#5]
#4 
Would it be possible for you to provide some demos of the missing files such as 'spots_data.pickle', 'parking_maneuvers.pickle', 'waypoints_graph.pickle' and 'agents_data.pickle' ?

**Comment by XuShenLZ** [comment]
Hi thank you very much for your interest! We are currently working on the paper manuscript for this part of the work so relevant data files are not made public yet. We will let you know once they are available
